services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "5001:5001"

  postgres:
    image: postgres:17
    container_name: applyo-pg
    # ports:
    #   - "5433:5432"
    environment:
      POSTGRES_DB: applyo_db
      POSTGRES_USER: applyo_developer
      POSTGRES_PASSWORD: applyo_password
    volumes:
      - applyo_data:/var/lib/postgresql/data

volumes:
    applyo_data:
